### ISSUE TITLE
Parent class for LOB exceptions

### ISSUE THREAD

**Issue by jbarbede** [lob/lob-php#100]
Hi, it would be great that any exception thrown by LOB library extends a parent LobException class.

Right now it is kind of annoying to catch LOB exceptions because it requires either to try/catch every single type of LOB exception or make a try / catch on the PHP base class Exception and most of the time you don't want to do that.

**Comment by mpiercy827** [comment]
Hi @jbarbede, thanks for bringing this to our attention. We'll be working on a fix soon and will keep you updated with it's progress.

**Comment by mpiercy827** [comment]
@jbarbede this change is present in v3.0.2. Thanks again for opening this issue!
