### ISSUE TITLE
All 100% Coverage Enforcement

### ISSUE THREAD

**Issue by leore** [lob/lob-php#17]

**Comment by joshstrange** [comment]
I'd be happy to assist in this endeavor but honestly I'm not sure why it's not already at 100%. AFAICT all code paths should be hit by the tests (especially in my most recent pull request). If someone could point out what is missing (or more specifically why coveralls is complaining when it looks like it should be fine) then I can fix it or add tests as needed.

**Comment by joshstrange** [comment]
It looks like #63 will make get lob-php to 100%

**Comment by joshstrange** [comment]
This can be closed now. [![Coverage Status](https://img.shields.io/coveralls/lob/lob-php.svg)](https://coveralls.io/r/lob/lob-php?branch=master)
