### ISSUE TITLE
Update Existing Address

### ISSUE THREAD

**Issue by upwebdesign** [lob/lob-php#34]
Im not sure if I am overlooking this, but I think there needs to be a PUT method to update addresses. I am running into issues with having to delete addresses for a user just to update their address in Lob. Is there another way?

**Comment by mgartner** [comment]
Updating addresses is not allowed so we maintain an accurate historical record of the destinations of every item we mail out. If you want to "change" an address, you can simply create a new one and update the address ID in your records. There is no need to delete the old address, but you can if you desire.

**Comment by upwebdesign** [comment]
OK, I understand why, but I think for my application (or any application) it may be best for me to store address information on my side and send Lob the full address (instead of a Lob address id) each time I create a postcard or check. I guess I was hoping to be able to use Lob as a true address book (maintaining single unique addresses for customers), which it appears it is not due to the redundancy and that is OK. Thanks for taking the time to reply back.
