### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by vijaykc** [lob/lob-php#46]
This is what i requested:

==============
require '../vendor/autoload.php';

$lob = new \Lob\Lob('TEST_KEY');

$check = $lob->addresses()->verify(array(
      'address_line1'     => '185 Berry Street234',
      'address_city'      => 'San Francisco',
      'address_state'     => 'CA',
      'address_zip'       => '94107'
    ));

print_r($check);
================

I get this issue when invalid address. Any idea?

Fatal error: Uncaught exception ResourceNotFoundException

**Comment by brianseitel** [comment]
Hi Vijay!

The value you put into `address_line1` is invalid. This is returning an `Address Not Found` exception, which tells us that the address is not a valid address.

Try `185 Berry St` instead of `185 Berry St234`.

**Comment by vijaykc** [comment]
Hi Brian,

Why is should return invalid address instead of Uncaught exception no?

Thanks,
Vijay

**Comment by brianseitel** [comment]
You'll need to catch it on your own.

```php
require '../vendor/autoload.php';

$lob = new \Lob\Lob('test_b6c16cc37fd315572ba1aa69319241a4a6b');

try {
  $check = $lob->addresses()->verify(array(
  'address_line1' => '185 Berry Street234',
  'address_city' => 'San Francisco',
  'address_state' => 'CA',
  'address_zip' => '94107'
  ));
} catch (ResourceNotFoundException $e) {
  echo "Resource not found!";
}
```

**Comment by vijaykc** [comment]
Thanks Brian.

**Comment by vijaykc** [comment]
still same errror.

Fatal error: Uncaught exception 'Lob\Exception\ResourceNotFoundException' with message 'Address Not Found' in E:\xampp\htdocs\clients\lexicon\sitting-solution\lob\lob-php-master\src\Lob\Resource.php:120 Stack trace: #0 E:\xampp\htdocs\clients\lexicon\sitting-solution\lob\lob-php-master\src\Lob\Resource\Addresses.php(27): Lob\Resource->sendRequest('POST', 'v1', '1.2.3', 'verify', Array, Array) #1 E:\xampp\htdocs\clients\lexicon\sitting-solution\lob\lob-php-master\examples\create_check.php(12): Lob\Resource\Addresses->verify(Array) #2 {main} thrown in E:\xampp\htdocs\clients\lexicon\sitting-solution\lob\lob-php-master\src\Lob\Resource.php on line 120

it doesn't work. any other suggestion?

**Comment by brianseitel** [comment]
Apologies. The exception is namespaced to `Lob\Exception\ResourceNotFound`, so you need to catch that:

```php
try {
  ...
} catch (Lob\Exception\ResourceNotFoundException $e) {
  echo "Resource not found!";
}
```

**Comment by vijaykc** [comment]
Great. It worked. Thanks Brian.
