### ISSUE TITLE
[Lob\Exception\UnexpectedErrorException]     An Unexpected Error has occurred. 

### ISSUE THREAD

**Issue by minhajresgef** [lob/lob-php#57]
[Lob\Exception\UnexpectedErrorException]  
  An Unexpected Error has occurred. 

Can anyone please explain??
(I was trying with test api key)

**Comment by ami** [comment]
Hey @minhaj-resgef - could you check out your logs on your dashboard and check out the corresponding log? That should give you more information -> https://dashboard.lob.com/#/logs?page=1

**Comment by ami** [comment]
Closing as this isn't related to lob-php specifically, please contact support@lob.com for Lob API specific errors!
