### ISSUE TITLE
Change Guzzle dependency to guzzlehttp/guzzle

### ISSUE THREAD

**Issue by joshstrange** [lob/lob-php#62]
I get this message when installing:

Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

Should be as easy as changing the package name in composer. Also just to note you are using guzzle 3 and guzzle 6 is out now, not a huge deal just thought I'd throw that out there.

**Comment by elnaz** [comment]
Thanks @joshstrange, we'll take a look. PRs welcome though!

**Comment by joshstrange** [comment]
@elnaz Well I just found some time to take a look at this (it's not a pressing matter really just something I noticed and wanted to mention) and was going to fork the repo to upgrade guzzle and the update the code as needed but I see you have already forked it and appear to have started work on it. Let me know if I can help any.

**Comment by elnaz** [comment]
@joshstrange I was taking a stab at it but please go ahead!

**Comment by joshstrange** [comment]
@elnaz I just posted a pull request, let me know if you see any issues or have any questions.

**Comment by elnaz** [comment]
Excellent! Thanks for your contribution. I'll take a look before the end of the week.

**Comment by joshstrange** [comment]
Closing this issue as the pull request encompasses all of this
