### ISSUE TITLE
How i can get Error Code?

### ISSUE THREAD

**Issue by vijaykc** [lob/lob-php#64]
LOB explaig error codes here.  
https://lob.com/docs/php#errors

I am using address verification. How i can get error codes? Does lop-php implemented error code?

`try {
	  $check = $lob->addresses()->verify(array(
	  'address_line1' => $billing_address,
	  'address_city' => $billing_city,
	  'address_state' => $billing_state,
	  'address_zip' => $billing_zip,
	  'address_country' => $billing_country
	  ));
	} catch (Lob\Exception\ResourceNotFoundException $e) {}`

Or Is there a other way to check address verification instead of exception?

Thanks in advance. 

Also Is there a way to check if LOB is active? Sometime it will down and API request fail.

**Comment by dmlittle** [comment]
@vijaykc the wrapper does surface the error codes from the API. Below is a little snippet how to catch the error codes for address verification:

```php
<?php
$lob = new \Lob\Lob('YOUR_API_KEY');

try {
  $address = $lob->addresses()->verify(array(
    'address_line1'    => '185 WRONG Street',
    'address_city'      => 'San Francisco',
    'address_state'    => 'CA',
    'address_zip'      => '94107'
  ));

  print_r($address);
} catch (Exception $e) {
  echo 'Caught Exception: ',  $e->getMessage(), " (statusCode: ", $e->getCode() ,")\n";
}
?>
```

In terms of our API status, you can find any information regarding any ongoing issues at [status.lob.com](http://status.lob.com/). We haven't had any major outages recently so I'm not sure why the request would fail. Let us know if you have any other questions.
