### ISSUE TITLE
Call to a member function getBody() on null

### ISSUE THREAD

**Issue by aarondfrancis** [lob/lob-php#85]
Hey again, 

I'm getting another error from time to time in a catch block.

The exception:
```
Call to a member function getBody() on null at vendor/lob/lob-php/src/Lob/Resource.php:107)
```

in Resource.php:107, which is (in my version)

```php
} catch (GuzzleException $e) {
    // The line below
    $responseErrorBody = strval($e->getResponse()->getBody());
    $errorMessage = $this->errorMessageFromJsonBody($responseErrorBody);
    $statusCode = $e->getResponse()->getStatusCode();

    // ...
```

**Comment by aarondfrancis** [comment]
I believe Guzzle has a `hasResponse` method.

http://docs.guzzlephp.org/en/stable/quickstart.html?highlight=exceptions#exceptions

**Comment by dmlittle** [comment]
@aarondfrancis do you happen to have an example payload that triggers or has triggered the exception? What method were you using?

**Comment by dmlittle** [comment]
Also, what version of the wrapper are you currently using?

**Comment by aarondfrancis** [comment]
From my composer.lock:

```json
"name": "lob/lob-php",
"version": "v2.1.1",
"source": {
    "type": "git",
    "url": "https://github.com/lob/lob-php.git",
    "reference": "f74c6a75cac247691762580fccce8cbe264c4b37"
},
```

Not sure what the payload is, but if I see another one I'll grab it and post back!

**Comment by dmlittle** [comment]
@aarondfrancis I haven't been able to reproduce this error nor find anything in our logs that would indicate there's an issue with our API or wrapper regarding this issue. 

I'll be closing this issue now but feel free to comment on this issue or message support@lob.com if you see this problem again.

**Comment by aarondfrancis** [comment]
It seems like you shouldn't call `getBody` on a `getResponse` knowing that `getResponse` can sometimes return null.

Even if it's a network issue, I believe the library should handle that gracefully.

Why not call `hasResponse` before trying to call `getBody`?

**Comment by aarondfrancis** [comment]
Please check out this SO post: https://stackoverflow.com/a/40644585.

> While the answers above are good they will not deal with network errors ...

> It's better in this case to expect RequestException and check for a response.

>  If there are network errors, we need to ensure the application doesn't crash
