### ISSUE TITLE
Expose Rate Limit headers

### ISSUE THREAD

**Issue by AndreiIgna** [lob/lob-php#86]
A great addition to the PHP API would be Rate Limiting info. While using the API, a RateLimiting exception is shows if this happens, but with no additional info.
Each API requests has this kind of data in headers but there's no way to access it.
Adding a method to access the headers on requests would solve this

Cheers

**Comment by ami** [comment]
Hey @AndreiIgna,

Please submit your first request (Plans API) to Lob support (support@lob.com) - this is a general Lob feature request which isn't related directly to the PHP library.

As far as accessing headers, this is definitely something we want to add. Feel free to submit a PR for this if you'd like!

I will be modifying this issue to only incorporate the header request - hope you don't mind!
