### ISSUE TITLE
CURL Reset Error

### ISSUE THREAD

**Issue by biswajit-paul** [lob/lob-php#92]
Hi,

I am getting this error on staging server:
`PHP Fatal error:  Call to undefined function GuzzleHttp\Handler\curl_reset() in /home/........./vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 78`.

PHP version is 5.4

Please help.

**Comment by dmlittle** [comment]
@biswajit-paul I'm unable to reproduce the error you're seeing on your end. In order to try to get more details as to what is causing this issue, could you provide us with the version of PHP and the Lob library you're currently using?

**Comment by biswajit-paul** [comment]
@dmlittle 
Thank you for your quick response. 

I have upgraded PHP version from 5.4 to 5.6 and the issue is solved. One thing I would like to inform that the US address verification response is quite slow. It takes some time when we try to verify bulk addresses. Can we get a little bit faster response?

Again, thank you and keep up your good work.

**Comment by dmlittle** [comment]
@biswajit-paul glad to hear you were able to solve the issue.

As for any performance or Lob specific questions (not related to the PHP Library), please contact support@lob.com.
